COMP: Work around H5DataSpace WASI missing symbol
See:

- https://llvm.org/docs/FAQ.html#what-is-this-llvm-global-ctors-and-global-i-a-stuff-that-happens-when-i-include-iostream
- https://stackoverflow.com/questions/31691280/what-does-global-sub-i-mean-in-nm-output

To address:

```
Error: failed to run main module `wasi-build/elastix.wasi.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0xf1ee5 - <unknown>!abort
           1: 0x106856 - __cxa_allocate_exception
                           at /ITKWebAssemblyInterface/src/exceptionShim.cxx:28:3
           2: 0x7284ab - <unknown>!_GLOBAL__sub_I_H5DataSpace.cpp
           3: 0x42832 - <unknown>!__wasm_call_ctors
           4: 0x16840c8 - _initialize_local
                           at /ITKWebAssemblyInterface/src/initialization.cxx:59:5
           5: 0x1684082 - _start
                           at /ITKWebAssemblyInterface/src/initialization.cxx:90:3
```